### ISSUE TITLE
Add vanderspek en Bakker 2017 data

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas-data#1]
It would be cool to add the data from this article https://doi.org/10.1002/2016WR019704

which @martinvonk already collected here: https://github.com/pastas/test-datasets/tree/main/vanderspek_bakker_2017

**Comment by martinvonk** [comment]
Metadata Table [https://agupubs.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2F2016WR019704&file=wrcr22532-sup-0001-2016WR019704-s01.pdf](https://agupubs.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2F2016WR019704&file=wrcr22532-sup-0001-2016WR019704-s01.pdf)
